name: Real Test Sub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write # اجازه حیاتی برای Push کردن
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Raw Configs
        run: |
          curl -L -o raw.txt "https://raw.githubusercontent.com/barry-far/V2ray-config/main/Splitted-By-Protocol/vless.txt"
          grep "^vless://" raw.txt | head -n 100 > unique.txt

      - name: Run Python Diagnostic Test
        run: python3 test_configs_final.py unique.txt subscription.txt

      - name: Commit & Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add subscription.txt
          git commit -m "Update working configs: $(date)" || exit 0
          git push
