name: Real Test Sub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Get Raw
        run: |
          curl -L -o raw.txt "https://raw.githubusercontent.com/barry-far/V2ray-config/main/Splitted-By-Protocol/vless.txt"
          grep "^vless://" raw.txt | head -n 100 > unique.txt

      - name: Install PyDeps
        run: pip install requests

      - name: Execute Python Test
        run: python3 test_configs_final.py unique.txt subscription.txt

      - name: Commit
        run: |
          git config --global user.name "mirsub-bot"
          git config --global user.email "bot@mirsub.com"
          touch subscription.txt # مطمئن شدن از وجود فایل
          git add subscription.txt
          git commit -m "Update subscription" || exit 0
          git push
